export const copy = {
  products: "ສິນຄ້າ",
  categories: "ຫມວດຫມູ່",
  search: "ຄົນຫາຊື່ / ບາຣໂຄດ",
  add: "ເພີມ",
  addProduct: "ເພີມສິນຄ້າ",
  editProduct: "ແກ້ສິນຄ້າ",
  addCategory: "ເພີມຫມວດ",
  editCategory: "ແກ້ຫມວດ",
  save: "ບັນທຶກ",
  cancel: "ຍົກເລີກ",
  delete: "ລົບ",
  deleting: "ກຳລັງລົບ…",
  saving: "ກຳລັງບັນທຶກ…",
  name: "ຊື່",
  barcode: "ບາຣໂຄດ",
  scanBarcode: "ສະແກນບາຣໂຄດ",
  scanTitle: "ສະແກນບາຣໂຄດ",
  scanHint: "ວາງບາຣໂຄດໃຫ້ຢູ່ໃນກອບ — ຈະກອກໃຫ້ອັດຕະໂນມັດ",
  scanStarting: "ກຳລັງເປີດກ້ອງ…",
  scanPermissionDenied: "ບໍ່ໄດ້ອະນຸຍາດໃຊ້ກ້ອງ — ເປີດສິດໃນຕັ້ງຄ່າເຄື່ອງ",
  scanNoCamera: "ບໍ່ພົບກ້ອງໃນເຄື່ອງນີ້",
  scanError: "ເປີດກ້ອງບໍ່ສຳເລັດ",
  toastBarcodeScanned: "ສະແກນບາຣໂຄດສຳເລັດ",
  switchCamera: "ປ່ຽນກ້ອງ",
  sku: "SKU",
  category: "ຫມວດຫມູ່",
  noCategory: "ບໍ່ມີຫມວດ",
  allCategories: "ທັງໝົດ",
  sellPrice: "ລາຄາຂາຍ",
  costPrice: "ລາຄາທຶນ",
  stock: "ສະຕັອກ",
  minStock: "ສະຕັອກຕ່ຳສຸດ",
  image: "ຮູບສິນຄ້າ",
  uploadImage: "ອັບໂຫລດຮູບ",
  changeImage: "ປ່ຽນຮູບ",
  removeImage: "ລົບຮູບ",
  imageHint: "ແຕະເພື່ອເລືອກຮູບ JPG / PNG",
  uploading: "ກຳລັງອັບໂຫລດ…",
  imageTypeError: "ກະລຸນາເລືອກໄຟລ໌ຮູບ",
  lowStockOnly: "ສະຕັອກຕ່ຳ",
  clearSearch: "ລ້າງຄົ້ນຫາ",
  filters: "ຕົວກອງ",
  emptyProducts: "ບໍ່ມີສິນຄ້າ",
  emptyCategories: "ບໍ່ມີຫມວດຫມູ່",
  confirmDeleteProduct: "ລົບສິນຄ້ານີ້ບໍ?",
  confirmDeleteCategory: "ລົບຫມວດນີ້ບໍ?",
  deleteHint: "ສິນຄ້າຈະຖືກປິດໃຊ້ງານ",
  loadError: "ໂຫລດຂໍ້ມູນບໍ່ສຳເລັດ",
  saveError: "ບັນທຶກບໍ່ສຳເລັດ",
  barcodeDup: "ບາຣໂຄດຊ້ຳ",
  productCount: "ສິນຄ້າ",
  lowStockBadge: "ສະຕັອກຕ່ຳ",
  noManage: "ທ່ານບໍ່ມີສິທທິຈັດການສິນຄ້າ",
  toastProductCreated: "ສ້າງສິນຄ້າສຳເລັດ",
  toastProductUpdated: "ບັນທຶກສິນຄ້າສຳເລັດ",
  toastProductDeleted: "ລົບສິນຄ້າສຳເລັດ",
  toastCategoryCreated: "ສ້າງຫມວດສຳເລັດ",
  toastCategoryUpdated: "ບັນທຶກຫມວດສຳເລັດ",
  toastCategoryDeleted: "ລົບຫມວດສຳເລັດ",
  toastLoginOk: "ເຂົ້າລະບົບສຳເລັດ",
  toastLogoutOk: "ອອກຈາກລະບົບສຳເລັດ",
} as const;
