export const salesCopy = {
  title: "ປະຫວັດຂາຍ",
  empty:
    "ຍັງບໍ່ມີປະຫວັດຂາຍ",
  pending: "ລໍຖ້າ sync",
  failed: "sync ລົ້ມເຫຼວ",
  synced: "ສົ່ງແລ້ວ",
  syncing: "ກຳລັງສົ່ງ",
  cash: "ເງິນສົດ",
  transfer: "ໂອນເງິນ",
  items: "ລາຍການ",
  retry: "ລອງ sync ໃໝ່",
  loadError:
    "ໂຫລດປະຫວັດບໍ່ສຳເລັດ",
  noPermission:
    "ທ່ານບໍ່ມີສິດເບິ່ງປະຫວັດຂາຍ",
  detailTitle: "ລາຍລະອຽດບິນ",
  amountDue: "ຍອດຊຳລະ",
  amountReceived: "ຮັບເງິນ",
  change: "ເງິນທອນ",
  qty: "ຈຳນວນ",
  unitPrice: "ລາຄາ",
  lineTotal: "ລວມ",
  subtotal: "ລວມລາຍການ",
  billDiscount: "ສ່ວນຫຼຸດບິນ",
  close: "ປິດ",
  noItems:
    "ບໍ່ພົບລາຍການສິນຄ້າ",
  slip: "ສະລິບໂອນ",
  soldAt: "ເວລາຂາຍ",
  filterAll: "ທັງໝົດ",
  filterNeedsSync: "ລໍຖ້າ sync",
  filterToday: "ມື້ນີ້",
  filter7d: "7 ວັນ",
  filterPeriod: "ຊ່ວງເວລາ",
  filterPayment: "ວິທີຊຳລະ",
  filterStatus: "ສະຖານະ sync",
  filters: "ຕົວກອງ",
  applyFilters: "ໃຊ້ຕົວກອງ",
  clearFilters: "ລ້າງຕົວກອງ",
  emptyFiltered:
    "ບໍ່ພົບບິນຕາມຕົວກອງ",
} as const;