export const copy = {
  title: "ຂາຍ",
  searchPlaceholder: "ຄົ້ນຫາຊື່ / ລະຫັດ / ສະແກນບາຣໂຄດ",
  searchEmpty: "ພິມຄົ້ນຫາ ຫຼື ສະແກນບາຣໂຄດ",
  notFound: "ບໍ່ພົບສິນຄ້າ",
  cart: "ກະຕ່າ",
  cartEmpty: "ກະຕ່າວ່າງ — ສະແກນ ຫຼື ຄົ້ນຫາສິນຄ້າ",
  stock: "ສະຕັອກ",
  add: "ເພີມ",
  remove: "ລົບ",
  discount: "ສ່ວນຫຼຸດ",
  lineDiscount: "ສ່ວນຫຼຸດລາຍການ",
  billDiscount: "ສ່ວນຫຼຸດທັງບິນ",
  discountPercent: "%",
  discountAmount: "₭",
  discountPreview: "ຫຼັງຫຼຸດ",
  apply: "ໃຊ້",
  clearDiscount: "ລ້າງສ່ວນຫຼຸດ",
  subtotal: "ລວມລາຍການ",
  total: "ລວມ",
  pay: "ຊຳລະເງິນ",
  payTitle: "ຊຳລະເງິນ",
  amountDue: "ຍອດທີ່ຕ້ອງຊຳລະ",
  cash: "ເງິນສົດ",
  transfer: "ໂອນເງິນ",
  amountReceived: "ຮັບເງິນ",
  change: "ເງິນທອນ",
  confirmCash: "ຢືນຢັນຮັບເງິນ",
  confirmTransfer: "ຢືນຢັນວ່າກວດສະລິບແລ້ວ",
  transferHint: "ໃຫ້ລູກຄ້າສະແກນ QR ແລ້ວກວດສະລິບເອງ",
  qrPlaceholder: "ຍັງບໍ່ມີ QR — ຕັ້ງຄ່າໃນເມນູຕັ້ງຄ່າ",
  accountPlaceholder: "ບັນຊີຮ້ານ (ຍັງບໍ່ໄດ້ຕັ້ງຄ່າ)",
  bankPlaceholder: "BCEL One / ໂອນເງິນ",
  insufficient: "ເງິນທີ່ຮັບບໍ່ພໍ",
  successTitle: "ຂາຍສຳເລັດ",
  successContinue: "ຂາຍຕໍ່",
  cancel: "ຍົກເລີກ",
  noPermission: "ທ່ານບໍ່ມີສິດຂາຍ",
  syncNeeded: "ຍັງບໍ່ມີສິນຄ້າໃນເຄື່ອງ — ໄປໜ້າສິນຄ້າແລ້ວກົດດຶງຂໍ້ມູນ",
  captureSlip: "ຖ່າຍຮູບສະລິບ",
  retakeSlip: "ຖ່າຍໃໝ່",
  slipAttached: "ຕິດສະລິບແລ້ວ",
  slipRequired: "ກະລຸນາຖ່າຍຮູບສະລິບກ່ອນຊຳລະ",
  slipUploading: "ກຳລັງອັບໂຫລດສະລິບ…",
  slipUploadError: "ອັບໂຫລດສະລິບບໍ່ສຳເລັດ",
  slipTypeError: "ກະລຸນາເລືອກໄຟລ໌ຮູບ",
  slipCameraHint: "ວາງສະລິບໃຫ້ຢູ່ໃນກອບ — ກົດປຸ່ມຖ່າຍ",
  slipShutter: "ຖ່າຍ",
  slipCameraStarting: "ກຳລັງເປີດກ້ອງ…",
  slipPermissionDenied: "ບໍ່ໄດ້ອະນຸຍາດໃຊ້ກ້ອງ — ເປີດສິດໃນຕັ້ງຄ່າເຄື່ອງ",
  slipNoCamera: "ບໍ່ພົບກ້ອງໃນເຄື່ອງນີ້",
  slipCameraError: "ເປີດກ້ອງບໍ່ສຳເລັດ",
  switchCamera: "ປ່ຽນກ້ອງ",
  scanBarcode: "ສະແກນບາຣໂຄດ",
  toastAddedToCart: "ເພີມກະຕ່າແລ້ວ",
  saleQueuedOffline: "ບິນຖືກບັນທຶກໃນຄິວ sync",
  salePersistError: "ບັນທຶກການຂາຍບໍ່ສຳເລັດ",
  saleQueuedHint: "ຈະ sync ເມື່ອກັບອອນລາຍ",
  saleShiftRequired: "ກະລຸນາເປີດກະກ່ອນຂາຍ",
  outOfStockWarn: "ສະຕັອກ 0 — ເພີມແລ້ວ (ເຕືອນ)",
} as const;
