export const reportsCopy = {
  title: "ລາຍງານ",
  noPermission: "ທ່ານບໍ່ມີສິດເບິ່ງລາຍງານ",
  offline: "ຕ້ອງອອນລາຍເພື່ອເບິ່ງລາຍງານ",
  loadError: "ໂຫລດລາຍງານບໍ່ສຳເລັດ",
  back: "ກັບ",
  daily: "ຍອດຂາຍລາຍວັນ",
  profit: "ກຳໄລຂັ້ນຕົ້ນ",
  top: "ສິນຄ້າຂາຍດີ",
  shift: "ປິດກະ / X-Z",
  date: "ວັນທີ",
  today: "ມື້ນີ້",
  d7: "7 ວັນ",
  d30: "30 ວັນ",
  custom: "ກຳນົດເອງ",
  from: "ຈາກ",
  to: "ຫາ",
  totalSales: "ຍອດຂາຍລວມ",
  cash: "ເງິນສົດ",
  transfer: "ໂອນເງິນ",
  bills: "ຈຳນວນບິນ",
  items: "ລາຍການ",
  revenue: "ລາຍໄດ້ (Revenue)",
  cogs: "ຕົ້ນທຶນ (COGS)",
  grossProfit: "ກຳໄລຂັ້ນຕົ້ນ",
  margin: "ອັດຕາກຳໄລ",
  rank: "#",
  product: "ສິນຄ້າ",
  qty: "ຊິ້ນ",
  sales: "ຍອດຂາຍ",
  stock: "ຄົງເຫຼືອ",
  emptyTop: "ບໍ່ມີຂໍ້ມູນຂາຍໃນຊ່ວງນີ້",
  paymentSplit: "ແຍກຕາມວິທີຊຳລະ",
  topChart: "ຈຳນວນຂາຍຕາມສິນຄ້າ",
} as const;

export const shiftCopy = {
  title: "ກະເຮັດວຽກ",
  open: "ເປີດກະ",
  opening: "ກຳລັງເປີດກະ...",
  openOk: "ເປີດກະແລ້ວ",
  openError: "ເປີດກະບໍ່ສຳເລັດ",
  noShift: "ຍັງບໍ່ໄດ້ເປີດກະ — ເປີດກະກ່ອນຂາຍ",
  currentOpen: "ກະເປີດຢູ່",
  xReport: "X-Report",
  zReport: "Z-Report (ປິດກະ)",
  close: "ປິດ",
  print: "ພິມ",
  total: "ຍອດຂາຍລວມ",
  cash: "ເງິນສົດ",
  transfer: "ໂອນເງິນ",
  expectedCash: "ເງິນສົດຕາມລະບົບ",
  countedCash: "ນັບໄດ້ຈິງ",
  diff: "ສ່ວນຕ່າງ",
  bills: "ຈຳນວນບິນ",
  confirmClose: "ຢືນຢັນປິດກະ",
  closing: "ກຳລັງປິດກະ...",
  closeOk: "ປິດກະແລ້ວ",
  closeError: "ປິດກະບໍ່ສຳເລັດ",
  loadError: "ໂຫລດກະບໍ່ສຳເລັດ",
  history: "ປະຫວັດກະ",
  emptyHistory: "ຍັງບໍ່ມີປະຫວັດກະ",
  statusOpen: "ເປີດ",
  statusClosed: "ປິດແລ້ວ",
  offline: "ຕ້ອງອອນລາຍເພື່ອຈັດການກະ",
} as const;
