export const settingsCopy = {
  title: "ຕັ້ງຄ່າ",
  receiptSection:
    "ຂໍ້ມູນຮ້ານ / ໃບບິນ",
  storeName: "ຊື່ຮ້ານ",
  address: "ທີ່ຍູ່",
  phone: "ເບອນທະລະສັບ",
  bankName: "ຘານາຄານ",
  bankAccount: "ເລກບັຍຊີ",
  logo: "Logo",
  qr: "QR ໂອນ",
  width: "ຄວາມກວ້າງໃບບິນ",
  width58: "58mm",
  width80: "80mm",
  thanks: "ຂໍ້ຄວາມຂອບໃຈ",
  save: "ບັນທຶກ",
  saving: "ກຳລັງບັນທຶກ...",
  offlineBanner:
    "ອອຟໄລນ໌ — ສະແດງຈາກ cache (ບັນທຶກບໍ່ໄດ້)",
  loadError: "ໂຫລດຕັ້ງຄ່າບໍ່ສຳເລັດ",
  saveOk: "ບັນທຶກສຳເລັດ",
  saveError: "ບັນທຶກບໍ່ສຳເລັດ",
  noPermission:
    "ທ່ານບໍ່ມີສິດແກ້ໄຂຕັ້ງຄ່າ",
  upload: "ອັປໂຫລດ",
  remove: "ລົບ",
  preview: "ພີວິວໃບບິນ",
  printerSection: "ຕັ້ງຄ່າເຄື່ອງພິມ",
  printerMode: "ວິທີພິມ",
  printerSystem: "ລະບົບ (Dialog)",
  printerThermal: "USB / Bluetooth",
  printerList: "ເຄື່ອງພິມ",
  printerRefresh: "ສະແກນ",
  printerNone: "ບໍ່ພົບເຄື່ອງພິມ",
  printerHintUsb: "USB: ເຊື່ອມສາຍ / OTG",
  printerHintBt: "Bluetooth: pair ໃນຕັ້ງຄ່າກ່ອນ",
  printerSelected: "ເຄື່ອງທີ່ເລືອກ",
  printerClear: "ລ້າງ",
  printerTest: "ທົດສອບພິມ",
  printerTestOk: "ພິມທົດສອບແລ້ວ",
  printerTestError: "ພິມທົດສອບບໍ່ສຳເລັດ",
  printerSaveOk: "ບັນທຶກເຄື່ອງພິມແລ້ວ",
  printerUnavailable: "ຕ້ອງເປີດແອັບ Tauri",
  themeSection: "ຮູບແບບສີ",
  themeLight: "ສະຫວ່າງ",
  themeDark: "ມືດ",
  themeSystem: "ຕາມລະບົບ",
  usersManage: "ຈັດການຜູ້ໃຊ້",
} as const;
