export const copy = {
  title: "ຜູ້ໃຊ້",
  search: "ຄົນຫາຊື່ / ອີເມວ",
  add: "ເພີ່ມຜູ້ໃຊ້",
  edit: "ແກ້ໄຂຜູ້ໃຊ້",
  name: "ຊື່",
  email: "ອີເມວ",
  password: "ລະຫັດຜ່ານ",
  passwordOptional: "ລະຫັດຜ່ານ (ປ່ອຍວ່າງຖ້າບໍ່ປ່ຽນ)",
  role: "ບົດບາດ",
  roleAdmin: "ເຈົ້າຂອງຮ້ານ",
  roleCashier: "ພະນັກງານຂາຍ",
  save: "ບັນທຶກ",
  saving: "ກຳລັງບັນທຶກ…",
  cancel: "ຍົກເລີກ",
  ban: "ປິດໃຊ້ງານ",
  unban: "ເປີດໃຊ້ງານ",
  delete: "ລົບ",
  deleting: "ກຳລັງລົບ…",
  banned: "ປິດໃຊ້ງານ",
  active: "ໃຊ້ງານ",
  you: "ທ່ານ",
  empty: "ຍັງບໍ່ມີຜູ້ໃຊ້",
  loadError: "ໂຫຼດຜູ້ໃຊ້ບໍ່ສຳເລັດ",
  offline: "ຕ້ອງອອນລາຍເພື່ອຈັດການຜູ້ໃຊ້",
  noPermission: "ທ່ານບໍ່ມີສິດຈັດການຜູ້ໃຊ້",
  saveOk: "ບັນທຶກສຳເລັດ",
  saveError: "ບັນທຶກບໍ່ສຳເລັດ",
  banOk: "ປິດໃຊ້ງານແລ້ວ",
  unbanOk: "ເປີດໃຊ້ງານແລ້ວ",
  deleteOk: "ລົບຜູ້ໃຊ້ແລ້ວ",
  deleteConfirmTitle: "ລົບຜູ້ໃຊ້ບໍ?",
  deleteConfirmDesc: "ການລົບບໍ່ສາມາດຍົກເລີກໄດ້",
  banConfirmTitle: "ປິດໃຊ້ງານຜູ້ໃຊ້ບໍ?",
  banConfirmDesc: "ຜູ້ໃຊ້ນີ້ຈະເຂົ້າລະບົບບໍ່ໄດ້",
  cannotBanSelf: "ບໍ່ສາມາດປິດໃຊ້ງານຕົວເອງໄດ້",
  cannotDeleteSelf: "ບໍ່ສາມາດລົບຕົວເອງໄດ້",
  passwordRequired: "ຕ້ອງໃສ່ລະຫັດຜ່ານ",
  passwordMin: "ລະຫັດຜ່ານຢ່າງນ້ອຍ 6 ຕົວອັກສອນ",
  formNewHint: "ປ້ອນຂໍ້ມູນແລ້ວກົດບັນທຶກ",
  formEditHint: "ແກ້ໄຂຂໍ້ມູນຜູ້ໃຊ້",
  sectionProfile: "ຂໍ້ມູນພື້ນຖານ",
  sectionRole: "ບົດບາດແລະສິດ",
  sectionPassword: "ຄວາມປອດພາຍ",
  roleAdminHint: "ຈັດການທຸກອັນແລະລາຍງານ",
  roleCashierHint: "ຂາຍສິນຄ້າແລະອອກໃບບິນ",
  showPassword: "ສະແດງ",
  hidePassword: "ເຊື່ອນ",
  previewNew: "ຜູ້ໃຊ້ໃໝ່",
  passwordHintCreate: "ຕ້ອງມີອີເມວແລະລະຫັດຜ່ານ",
  passwordHintEdit: "ປ່ອຍວ່າງຖ້າບໍ່ຕ້ອງການປ່ຽນ",
} as const;
